# Generated by Django 4.0.3 on 2022-03-25 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0002_userresume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BestJobsOutput',
        ),
        migrations.DeleteModel(
            name='MLRequest',
        ),
    ]
