# Generated by Django 4.0.3 on 2022-03-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0003_delete_bestjobsoutput_delete_mlrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresume',
            name='cities_input',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
