# Generated by Django 4.0.3 on 2022-03-27 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0004_userresume_cities_input'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresume',
            old_name='cities_input',
            new_name='city',
        ),
    ]
