from django.test import TestCase

# Create your tests here.
from apps.ml.rs.training import RecommenderSystem

class MLTests(TestCase):
    def test_rs_algorithm(self):
        input_data = {
            "resume_text": "Saima Munir\n\nPickering, ON | saima.b.munir@gmail.com | linkedin.com/in/saima-munir | github.com/saima1999\n\n\n\nSUMMARY OF QUALIFICATIONS\n\nAspiring software engineer looking to build purposeful, efficient and creative systems.\n\n1 year of industry experience in full-stack web development, databases and machine learning.\n\n\n\nEDUCATION\n\nRyerson University\t\t\t\t\t\t\t\t         \t             Toronto, ON\n\nBachelor of Engineering in Computer Engineering\t\t\t \t       \tExpected May 2022\n\n\n\nSKILLS\n\nFrontend \tJavaScript, ReactJS, HTML, CSS, Node.js, Webpack\n\nBackend \tPython Django, Django REST API\n\nDatabases \tSQL, Microsoft MySQL Server\n\nPlatform \t\tMicrosoft Azure \n\nData Science\tPython Libraries - Pandas, PyTorch, Numpy\n\nOther Languages\tC, Java, MATLAB, VHDL\n\n\n\nWORK EXPERIENCE\n\nOntario Power Generation \t\t\t\t\t\t\t\t           Pickering, ON\n\nSoftware Engineering Intern \t\t\t\t\t\t\t           July 2020 – July 2021\n\nDeveloped the full stack of an internal web application for centralizing decades of fuel channel inspection data to automate a portion of the inspection analysis process.\n\nDesigned and implemented a highly functional and efficient user interface which included data searching, data filtering and visual mapping tools, to help senior engineers and scientists to navigate through decades of inspection data. \n\nCreated internal APIs using Django REST Framework to store inspection data.\n\nThe stack used was ReactJS, HTML, CSS, Django, MySQL, Node.js and Webpack, and was deployed on the MS Azure platform.\n\nResponsible for testing code, documenting code, demonstrating the application to other innovation departments, and training users.\n\n\t          \t\t\t    \n\nCAPSTONE PROJECT\n\nDepartment of ECBE\t\t\t\t       \t\t       \t     Ryerson University | Toronto, ON\n\nML Driven Job Recommender System\t\t\t\t\t September 2021 – Present\n\nCollaborating in a team to design a machine learning driven job recommender system in Python.\n\nConducting research on Recommender Systems, NLP, LDA and clustering techniques.\n\nCompiling and recording design activity documentation.\n\n\n\nEXTRACURRICULAR EXPERIENCE\n\nIEEE EMBS\t \t\t\t\t\t\t       \t     Ryerson University | Toronto, ON Webmaster\t\t\t\t\t         \t            \t             \t      \t       \t  July 2021 - Present\n\nResponsible for maintaining and updating the group’s WordPress website using HTML and CSS. \n\nWomen in Engineering\t \t\t\t\t       \t \t     Ryerson University | Toronto, ON\n\nMentor\t\t\t\t\t\t\t  \t\t            \t       February 2018 - Present\n\nGuiding first year engineering students with navigating the transition from high school.\n\nOrganised outreach programs for girls grades 7-12 to introduce them to careers in STEM. \n\nMentored participants during workshops about CAD, Arduino, 3D Printing, simple circuits etc., while sharing personal experiences about being an engineering student."
        }
        computation = RecommenderSystem()
        response = computation.bestjobs_computations(input_data)
        #self.assertEqual('OK', response)